site_name: Concise Generation Guided
theme:
  name: material
nav:
  - 写在前面: index.md
  - AE: AutoEncoder.md
  - VAE: VAE.md
  - VQVAE: VQVAE.md
  - GAN: GAN.md
  - Diffusion series:
      - DDPM: DDPM.md
      - DDIM: DDIM.md
      - Latent Diffusion: LatentDiffusion.md
      - Stable Diffusion: StableDiffusion.md
      - Classifier-Guided Diffusion: ClassifierGuidedDiffusion.md
      - Classifier-Free Guidance: ClassifierFreeGuidance.md
      - Diffusion Posterior Sampling: DiffusionPosteriorSampling.md
  - Flow series:
      - Normalizing Flows: NormalizingFlows.md
      - Flow Matching: FlowMatching.md
      - Rectified Flow Matching: RectifiedFlowMatching.md