site_name: Concise Generation Guided
theme:
  name: material
nav:
  - 写在前面: index.md
  - AutoEncoder(AE): AutoEncoder.md
  - Variational AutoEncoder(VAE): VAE.md
  - Vector Quantized Variational AutoEncoder(VQVAE): VQVAE.md
  - Generative Adversarial Networks(GAN): GAN.md
  - Diffusion series:
      - DDPM: DDPM.md
      - DDIM: DDIM.md
      - Latent Diffusion: LatentDiffusion.md
      - Stable Diffusion: StableDiffusion.md
      - Classifier-Guided Diffusion: ClassifierGuidedDiffusion.md
      - Classifier-Free Guidance: ClassifierFreeGuidance.md
      - Diffusion Posterior Sampling: DiffusionPosteriorSampling.md
  - Flow series:
      - Normalizing Flows: NormalizingFlows.md
      - Flow Matching: FlowMatching.md
      - Rectified Flow Matching: RectifiedFlowMatching.md